---
# environment file for labpositiva.Ntp

- name: Create files ntp
  become: true
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items: "{{ _ntp_create_files | default([]) }}"
  when: _ntp_create_files is defined
