---
# task for labpositiva.Ntp

- name: Install packages via pip ntp
  become: true
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when: ntp_pip_dependencies is defined
  with_items: "{{ ntp_pip_dependencies | default([]) }}"
