---
# task file for labpositiva.Ntp

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ _ntp.templates | default([]) }}"
  when: _ntp.templates is defined
